name: CI

on:
  pull_request:

permissions:
  contents: read

defaults:
  run:
    working-directory: app

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Determine Bun version
        id: bun-version
        run: echo "BUN_VERSION=$(jq -r '.engines.bun' package.json)" >> $GITHUB_OUTPUT

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ steps.bun-version.outputs.BUN_VERSION }}

      - run: bun install --frozen-lockfile
      - run: bun test
        env:
          TOKEN_ENCRYPTION_KEY: AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Determine Bun version
        id: bun-version
        run: echo "BUN_VERSION=$(jq -r '.engines.bun' package.json)" >> $GITHUB_OUTPUT

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ steps.bun-version.outputs.BUN_VERSION }}

      - run: bun install --frozen-lockfile
      - run: bun typecheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Determine Bun version
        id: bun-version
        run: echo "BUN_VERSION=$(jq -r '.engines.bun' package.json)" >> $GITHUB_OUTPUT

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ steps.bun-version.outputs.BUN_VERSION }}

      - run: bun install --frozen-lockfile
      - run: bun lint
